language: node_js
node_js: lts/*

branches:
  except: /^nightly-.*$/

before_install:
  - export TZ=Asia/Shanghai COMMIT_ID=${TRAVIS_COMMIT::6}

script:
  - yarn run lint
  - yarn run test:unit
  - yarn run build

before_deploy:
  # Add tag if missing
  - if [ -z "$TRAVIS_TAG" ]; then
      export TRAVIS_TAG=nightly-$COMMIT_ID RELEASE_TITLE=$(date +'%Y%m%d-%H%M%S') &&
      export RELEASE_FILE=qb-web-$RELEASE_TITLE.zip &&
      git tag $TRAVIS_TAG &&
      echo tagged as $TRAVIS_TAG;
    fi
  # Pack for release
  # see https://github.com/qbittorrent/qBittorrent/pull/10485, fixed in qb v4.2.0
  - cp dist/public/{index,login}.html
  - cp INSTALL.md dist
  - zip -r $RELEASE_FILE dist

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: $RELEASE_FILE
  skip_cleanup: true
  overwrite: true
  prerelease: true
  name: $RELEASE_TITLE
  on:
    branch: master
